### ISSUE TITLE
Is there any instruction to show how to import examples into GUI flow？

### ISSUE THREAD

**Issue by luyufan498** [Xilinx/kv260-vitis#10]
Hi,

I want to modify the overlay examples to fit my design.  Is there any instruction about importing them into GUI?

I follow the tutorial here to build the application, but I don't know how to import them.
(https://xilinx.github.io/kria-apps-docs/main/build/html/docs/build_vitis_platform.html)

**Comment by vmayoral** [comment]
> Vitis tutorials in this repo https://github.com/Xilinx/Vitis-Tutorials/tree/2021.1/Vitis_Platform_Creation which you may find useful for GUI based flows.

+1, Vitis-Tutorials is the way to go. It was extremely useful for me in the past @luyufan498, when I was looking to meet a use case similar to yours. If you struggle with any of those, open a ticket there, I got good support at the time.
