### ISSUE TITLE
[Vivado 12-8300] Launch HLS failed! Please see vitis_hls.log for details.

### ISSUE THREAD

**Issue by 2018boyan** [Xilinx/kv260-vitis#12]
Please help me!
My System is Ubuntu 20.04.03(amd64)
The version of the Vitis is 2021.1. And I also source all of settings64.sh before I run;
root@Z370-AORUS-Gaming-7:/home/nvidia/prj_k26/kv260-vitis# source /opt/Xilinx_2021/Vivado/2021.1/settings64.sh 
root@Z370-AORUS-Gaming-7:/home/nvidia/prj_k26/kv260-vitis# source /opt/Xilinx_2021/Vitis_HLS/2021.1/settings64.sh 
root@Z370-AORUS-Gaming-7:/home/nvidia/prj_k26/kv260-vitis# source /opt/Xilinx_2021/Vitis/2021.1/settings64.sh 
root@Z370-AORUS-Gaming-7:/home/nvidia/prj_k26/kv260-vitis# make platform PFM=kv260_ispMipiRx_vcu_DP

The error is:
![image](https://user-images.githubusercontent.com/42407841/150958181-0c0ca47a-5925-4e92-981b-f14a28c02005.png)

****** Vivado v2021.1 (64-bit)
  **** SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
  **** IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
    ** Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.

source run_ippack.tcl -notrace
ERROR: '2201251806' is an invalid argument. Please specify an integer value.
    while executing
"rdi::set_property core_revision 2201251806 {component component_1}"
    invoked from within
"set_property core_revision $Revision $core"
    (file "run_ippack.tcl" line 1186)
INFO: [Common 17-206] Exiting Vivado at Tue Jan 25 18:06:44 2022...
ERROR: [IMPL 213-28] Failed to generate IP.
INFO: [HLS 200-111] Finished Command export_design CPU user time: 10.35 seconds. CPU system time: 0.53 seconds. Elapsed time: 12.13 seconds; current allocated memory: 473.184 MB.
command 'ap_source' returned error code
    while executing
"source /home/nvidia/prj_k26/kv260-vitis/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.runs/kv260_ispMipiRx_vcu_DP_v_frmbuf_wr..."
    ("uplevel" body line 1)
    invoked from within
"uplevel \#0 [list source $arg] "

INFO: [HLS 200-112] Total CPU user time: 47.03 seconds. Total CPU system time: 2.11 seconds. Total elapsed time: 49.24 seconds; peak allocated memory: 470.467 MB.
INFO: [Common 17-206] Exiting vitis_hls at Tue Jan 25 18:06:47 2022...
ERROR: [Vivado 12-8300] Launch HLS failed! Please see vitis_hls.log for details.
INFO: [Common 17-206] Exiting Vivado at Tue Jan 25 18:06:47 2022...

Thanks in advance!

**Comment by vdayananz** [comment]
Please install y2k22_patch for Vivado HLS and Vitis HLS tools to avoid 'Y2K22 Overflow Issue'.
Refer to the following Answer Record for obtaining the patch.

https://support.xilinx.com/s/article/76960?language=en_US

**Comment by 2018boyan** [comment]
> Please install y2k22_patch for Vivado HLS and Vitis HLS tools to avoid 'Y2K22 Overflow Issue'. Refer to the following Answer Record for obtaining the patch.
> 
> https://support.xilinx.com/s/article/76960?language=en_US

It works, thank you very much!
