### ISSUE TITLE
PetaLinux build process

### ISSUE THREAD

**Issue by zohourih** [Xilinx/kv260-vitis#4]
Where can I find PetaLinux BSPs or configuration to build PetaLinux for platforms provided in this repository? At least I would expect a custom device-tree config to be provided for each platform.

**Comment by chkohn** [comment]
@zohourih 
petalinux build instructions are here: https://xilinx.github.io/kria-apps-docs/master/docs/build_petalinux.html
device tree overlay fragments are available here for each platform: https://github.com/Xilinx/kv260-firmware

**Comment by zohourih** [comment]
@chkohn Thank you for the reply, I will check the documentation. Might be a good idea to put those links in the README of this repo, as well.
