### ISSUE TITLE
missing kv260-vitis-release-2020.2.2_k26/overlays/examples/smartcam/common/xf_common.hpp

### ISSUE THREAD

**Issue by gm300a** [Xilinx/kv260-vitis#8]
I got errors in `make overlay OVERLAY=smartcam`. The error message in log file are follows,
`
grep -i2 error overlays/examples/smartcam/v++_pp_pipeline_accel_4240.backup.log 
`
 Then I got ...
`
===>The following messages were generated while  performing high-level synthesis for kernel: pp_pipeline_accel Log file: /XXXX/kv260-vitis-release-2020.2.2_k26/overlays/examples/smartcam/_x/pp_pipeline_accel/pp_pipeline_accel/vitis_hls.log :
`
`
ERROR: [v++ 207-812] 'common/xf_common.hpp' file not found: /XXXX/kv260-vitis-release-2020.2.2_k26/overlays/examples/smartcam/xf_pp_pipeline_config.h:20:10
`
`
ERROR: [v++ 60-300] Failed to build kernel(ip) pp_pipeline_accel, see log for details: /XXXX/kv260-vitis-release-2020.2.2_k26/overlays/examples/smartcam/_x/pp_pipeline_accel/pp_pipeline_accel/vitis_hls.log
`
`
ERROR: [v++ 60-773] In '/XXXX/kv260-vitis-release-2020.2.2_k26/overlays/examples/smartcam/_x/pp_pipeline_accel/pp_pipeline_accel/vitis_hls.log', caught Tcl error: ERROR: [HLS 207-812] 'common/xf_common.hpp' file not found: /XXXX/kv260-vitis-release-2020.2.2_k26/overlays/examples/smartcam/xf_pp_pipeline_config.h:20:10
`
`
ERROR: [v++ 60-599] Kernel compilation failed to complete
`
`
ERROR: [v++ 60-592] Failed to finish compilation
`
`
INFO: [v++ 60-1653] Closing dispatch client.
`
where I can get this file?from include file, I will needs following files.
`
#include "common/xf_common.hpp"
`
`
#include "common/xf_utility.hpp"
`
`
#include "dnn/xf_preprocess.hpp"
`
`
#include "imgproc/xf_crop.hpp"
`
`
#include "imgproc/xf_cvt_color.hpp"
`
`
#include "imgproc/xf_cvt_color_1.hpp"
`
`
#include "imgproc/xf_duplicateimage.hpp"
`
`
#include "imgproc/xf_resize.hpp"
`
`
#include "xf_config_params.h"
`

**Comment by chkohn** [comment]
it sounds like you did not clone the git submodules or something went wrong during submodule checkout. Please make sure you use ``git clone --recursive`` when cloning this repo, see README file for details.

**Comment by gm300a** [comment]
Thank you. You are right. I didn't clone. also, I didn't run xsa creation flow.  
Recreation of the package with `git clone --recursive` and `make xsa `, then I could complete the `make overlay`. 
Strangely, even `make overlay` was finished without error, the files complained in the previous run still did not exist.
